### ISSUE TITLE
Adding `request_path` Causes Preformance Issue

### ISSUE THREAD

**Issue by benfalk** [deadtrickster/prometheus-plugs#2]
:wave: Recently I forked this library to add `request_path` as one of the items to watch : https://github.com/benfalk/prometheus-plugs/commit/c78bd3ba99f00ff3c226fac4cc3e150318f99973

After putting it through a stress test I notice that the performance gets slower and slower over time.  Bombarding my phoenix application with requests from locust starts with an average response time of ~20ms; however, as the test continues the average continues to grow well into a full second per request.  As soon as I remove the path label I've added in this fork the performance of a load test remains fairly constant through the entire stress test.

I've just started looking into this, if you have any ideas they would be greatly appreciated.

**Comment by benfalk** [comment]
### UPDATE

Every new lookup by id increases the histogram and counter tables.  As this table gets bigger the calls seem to get slower.  With an average request time of ~380 ms these two tables are at about 500 items

![screenshot from 2016-08-04 09-46-24](https://cloud.githubusercontent.com/assets/2657901/17406341/a23f0a0e-5a28-11e6-9ec7-67b450b91374.png)

Going to dig into this a bit more and see if I can reason what's up

**Comment by deadtrickster** [comment]
Hey, thank you for trying this library!
Let me quote [Prometheus Best Practices Guide](https://prometheus.io/docs/practices/naming/)

```
CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.
```

So if you randomize `request_path` in your tests you create new 'metric' or 'series' for each `request_path`.
This is why I didn't add this label myself.
Since metrics exported by prometheus-plugs are ETS based, I think you might hit ETS performance bottleneck. 

Hope this clarifies things a bit.

BTW can you share your test code?

**Comment by benfalk** [comment]
You're spot on.  What I really wanted to add was the "controller/method" used by Phoenix.  Would you mind if I took a stab at making a label for this metric?

> BTW can you share your test code?

The test harness I'm using is Locust: http://locust.io/

This is how I have the fork implemented in my code:
``` elixir
# called by the endpoint supervisor code Phoenix sets up
  defp configure_prometheus do
    Plug.PrometheusCollector.setup(labels: [:method, :path])
    Plug.PrometheusExporter.setup
  end
```

``` elixir
# in the `endpoint.ex` put down by Phoenix
  plug Plug.PrometheusCollector, [:method, :path]
  plug Plug.PrometheusExporter, path: "/metrics"
```

**Comment by deadtrickster** [comment]
Few thoughts:

My 'problem' with phoenix integration is that these plugs are 'low-level'. I place them long before phoenix router so I can measure stuff like static handlers, errors, sessions etc. Basically I see phoenix just like any other plugs collection.

Phoenix adds :phoenix_action, :phoenix_controller private fields to connection only when request is successfully routed. So other plugs can access them only when they are part of controller pipeline. In theory their presence can be detected by collector and respective labels emitted. 

Phoenix has built in instrumentation, like here: 
https://github.com/phoenixframework/phoenix/blob/9261d468c18c745b6b26e596b1f11f6a3499290c/lib/phoenix/controller/pipeline.ex#L109. Maybe create collector just for phoenix with instrumentation integration?

**Comment by benfalk** [comment]
Perhaps a new collector would be the way to go as you suggest.  Here is what I have so far and it works pretty well with the stress tests: https://github.com/benfalk/prometheus-plugs/commit/1f82d7b67aa05601237601a6a281309f9ca6430b.  I'll look into the instrumentation integration and see what that's all about :+1:

**Comment by benfalk** [comment]
What are your thoughts on making the labels more dynamic so a code change isn't required to the code base in order for a user of the lib to add extra labels?

**Comment by benfalk** [comment]
I was thinking something like this: https://github.com/benfalk/prometheus-plugs/commit/5dc5ba1434e2f534e1e0878ab499f9239221bf6b

**Comment by deadtrickster** [comment]
Hey, Cool! 

Something like

```elixir
defp label_value({label, fun}, conn) when is_function(fun, 2), do: fun.(label, conn)
defp label_value(fun, conn) when is_function(fun, 1), do: fun.(conn)
defp label_value(_, conn), do: :undefined 

plug Plug.PrometheusCollector, [:method, :path, 'phoenix-controller': fun (_label, conn) do: conn.private[phoenix_controller] end]
```
or like

```elixir
defp connection_private_value (label, conn) do
  conn.private[label]
end

plug Plug.PrometheusCollector, [:method, :path, 
    phoenix_controller: &connection_private_value/2, 
    phoenix_action: &connection_private_value/2]
```
Looks interesting.

Concerns: label set should be known at setup call time. i.e. metric family arity (labels set) can't be changed at runtime. Obviously no crashes, heavy works, etc.

**Comment by zanhsieh** [comment]
@deadtrickster do you mind to include how exactly to custom labels in your example project? thanks a lot.

**Comment by deadtrickster** [comment]
Here is my configuration that works with 0.9 version!

please expect few deprecation warnings after update!

```

config :prometheus, PlugsInstrumenter,
    labels: [:status_class, {:request_path, MyPlugLables}],
    duration_buckets: [10, 100, 1_000, 10_000, 100_000,
                      300_000, 500_000, 750_000, 1_000_000,
                      1_500_000, 2_000_000, 3_000_000],
    registry: :default
```

```
defmodule MyPlugLables do
  def label_value(:request_path, conn) do
    conn.request_path
  end
end
```

output:

```
http_request_duration_microseconds_bucket{status_class="server-error",request_path="/api/v1/[FILTERED]",le="500000"} 0
```
