### ISSUE TITLE
Latency calculation doesn't account for native time unit

### ISSUE THREAD

**Issue by seancribbs** [deadtrickster/prometheus-plugs#22]
The Erlang docs are pretty clear that the units on `:erlang.monotonic_time()` are determined by the runtime and not necessarily standard across operating systems. The `Prometheus.PlugPipelineInstrumenter` module doesn't [account for the difference between the unit of the result and the unit of the histogram](https://github.com/deadtrickster/prometheus-plugs/blob/master/lib/prometheus/plug_pipeline_instrumenter.ex#L139-L151).

You can determine the relative precision difference with `:erlang.convert_time_unit(1, duration_unit, :native)` (which on my system results in `1000` for the default `:microseconds` unit in the instrumentor). Once the factor is known, the observed timing can be scaled before recording. Note that `:erlang.convert_time_unit/3` will truncate values smaller than the target unit to 0, and so division by the factor is probably preferable.

**Comment by seancribbs** [comment]
The [`observe_duration` macro in `Prometheus.Histogram`](https://github.com/deadtrickster/prometheus.ex/blob/master/lib/prometheus/metric/histogram.ex#L123-L129) seems to have the same bug.

**Comment by seancribbs** [comment]
On second look, I think this is handled in the Erlang client? https://github.com/deadtrickster/prometheus.erl/blob/master/src/prometheus_time.erl

**Comment by deadtrickster** [comment]
yes :-)!

**Comment by seancribbs** [comment]
Sorry for the derp!
