### ISSUE TITLE
[Question] How to reduce the cardinality of request_path?

### ISSUE THREAD

**Issue by agung-kargo** [deadtrickster/prometheus-plugs#39]
Hi,

Thanks for providing this great library. I am using it now to put monitoring instrumentation in our Elixir code. I have question, for service that use REST api approach, where it is normal to put the id as url path like this: `GET /parent/child/<id>`, if I put `request_path` as label, the cardinality of that label would be huge. 

Is there any way we can filter/remove the `<id>` path? 
Would be helpful if there is any pointer how to do it?

Currently I put the custom label by this code
```elixir
defmodule AppWeb.Prometheus.PipelineInstrumenter do

  use Prometheus.PlugPipelineInstrumenter

  def label_value(:request_path, conn) do
    conn.request_path
  end
end
```

then the config is
```elixir
config :prometheus, AppWeb.Prometheus.PipelineInstrumenter,
  labels: [:status_class, :status_code, :method, :host, :scheme, :request_path],
  duration_buckets: [10, 100, 1_000, 10_000, 100_000,
                      300_000, 500_000, 750_000, 1_000_000,
                      1_500_000, 2_000_000, 3_000_000],
  registry: :default,
  duration_unit: :microseconds
```

Sorry to ask this noob question, I am still new in Elixir world

**Comment by calvin-kargo** [comment]
Hi, i think we can use compile-time route path provided by phoenix to standardize dynamic request path (https://hexdocs.pm/phoenix/Phoenix.Router.html#route_info/4) so we can get the string route pattern (like `/parent/child/:id`) from dynamic route (like `/parent/child/123`)

with that, we can adjust the label by
```
defmodule AppWeb.Prometheus.PipelineInstrumenter do

  use Prometheus.PlugPipelineInstrumenter
    
  def label_value(:request_path, conn) do
     case Phoenix.Router.route_info(AppWeb.Router, conn.method, conn.request_path, "") do
       %{route: route} -> route
       _ -> conn.request_path
   end
end
```

**Comment by agung-kargo** [comment]
Thanks @calvin-kargo  for the solution, it works!
