### ISSUE TITLE
Performance impact

### ISSUE THREAD

**Issue by timbuchwaldt** [deadtrickster/prometheus-plugs#4]
Hey Ilya, thanks for the work you put into this :)

There is a slight (ok.. huge) performance hit in the exporter plug. Due to calculating the data first, then checking for a route match, the data is calculated on every request, but during high application usage almost never used.

**Comment by deadtrickster** [comment]
Oh good spot!

**Comment by timbuchwaldt** [comment]
Already working on a fix, btw. Expect a PR soon

**Comment by deadtrickster** [comment]
Ah. ok :-) I'm working on Ecto integration btw (https://github.com/deadtrickster/prometheus-ecto) Feeback is welcome!

**Comment by timbuchwaldt** [comment]
Will give you some feedback for the ecto part once I tried, I have cobbled something together in a Phoenix app that seems close :)
